### ISSUE TITLE
Judging Error 1是什么问题啊

### ISSUE THREAD

**Issue by yuanguangxin** [chaoshxxu/virtual-judge#11]
还有就是进入contest后就会一直弹窗error

**Comment by chaoshxxu** [comment]
Can't reproduce.

**Comment by zhblue** [comment]
where is the latest version ?

**Comment by chaoshxxu** [comment]
Currently it's ONLY in http://vjudge.net

**Comment by zhblue** [comment]
clever choice, one instance of vjudge is good enough for everyone

**Comment by chaoshxxu** [comment]
, as long as the only one is stable. Thanks for support :)
